{{- if not .Values.secrets.useExisting }}
{{- if or (not (empty .Values.secrets.azureOpenAIApiKey)) (not (empty .Values.secrets.azureSearchApiKey)) (not (empty .Values.secrets.openAIApiKey)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlwebnet.fullname" . }}-secrets
  labels:
    {{- include "nlwebnet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.secrets.azureOpenAIApiKey) }}
  azure-openai-api-key: {{ .Values.secrets.azureOpenAIApiKey | b64enc }}
  {{- end }}
  {{- if not (empty .Values.secrets.azureSearchApiKey) }}
  azure-search-api-key: {{ .Values.secrets.azureSearchApiKey | b64enc }}
  {{- end }}
  {{- if not (empty .Values.secrets.openAIApiKey) }}
  openai-api-key: {{ .Values.secrets.openAIApiKey | b64enc }}
  {{- end }}
{{- end }}
{{- end }}